### ISSUE TITLE
Help or documentation required for setting up a dev enviroment

### ISSUE THREAD

**Issue by gigadani** [EntropyRy/Tunkki#18]
Tried to deploy the Docker stuff with `docker-compose up` but ran into several problems which seem to relate to PHP stuff. Either there are some prerequisites to satisfy or some stuff to do that I didn't do.

My local environment might of course be the reason for this, as I'm running Windows, equipped with WSL2 Debian and Docker Desktop. I can switch to a pure Linux environment if that helps but my strong guess is that my setup here isn't the issue.

I would appreciate it a lot if there was even a rudimentary step-by-step guide for setting this up! Doesn't have to be written minding the Win+WSL2 stuff. It can be a guide for a pure Linux environment.

Thanks a lot in advance!

**Comment by haivala** [comment]
done

**Comment by gigadani** [comment]
Thanks for providing a better Readme. 

But could you please still include a list of all prerequisites required for resulting in a successful deployment? Going through second or third step of that install guide halts because it seems I haven't guessed the correct versions of software to install; mainly PHP and all the extensions.

I'd like to say that "write it like I was an idiot", but _I really am_ an idiot 🐵

**Comment by haivala** [comment]
You don't need to guess anything. .env.example files have reasonable defaults

**Comment by gigadani** [comment]
No, I don't mean that. This is what I mean with the prerequisites:
- what PHP (version) should be installed?
- what PHP extensions should be installed?
- any other software requirements?

**Comment by haivala** [comment]
you should only need to have docker and docker-compose installed
