### ISSUE TITLE
Navigation bar links broken in English artist profile pages

### ISSUE THREAD

**Issue by tejeez** [EntropyRy/Tunkki#22]
I noticed some links point to wrong addresses when using the site in English. It seems to happen on every artist profile page, but just for example: https://entropy.fi/artist/Looney

The top bar links point to https://entropy.fi/join-us https://entropy.fi/events etc, whereas the correct addresses would be https://entropy.fi/en/join-us etc

I wasn't logged in (in case that's relevant).

**Comment by haivala** [comment]
Those artist profile pages should not be used as they have not been properly tested. Those should only be used as internal pages for people to see their full artist profile.

I need steps to reproduce. Everything seems to be working as expected.

I just noticed that Happotesti timetable links are wrong as they are self made.

**Comment by tejeez** [comment]
* Open https://entropy.fi/artist/Looney in private browsing so you're not logged in or anything
* Click "Join Us"
* 404 for me, it directs to https://entropy.fi/join-us

**Comment by haivala** [comment]
Yeah. that url should not be as a link anywhere

**Comment by haivala** [comment]
I fixed the links in Happotesti event info
